<?php
/**
 * KlarnaPayLater gateway.
 *
 * Generated by `bin/generate-give-gateways.php` — do not edit manually.
 *
 * @author    Pronamic <info@pronamic.eu>
 * @copyright 2005-2026 Pronamic
 * @license   GPL-2.0-or-later
 * @package   Pronamic\WordPress\Pay\Extensions\Give
 */

namespace Pronamic\WordPress\Pay\Extensions\Give\Gateways;

use Pronamic\WordPress\Pay\Core\PaymentMethods;
use Pronamic\WordPress\Pay\Extensions\Give\Gateway;

/**
 * KlarnaPayLater gateway class
 */
final class KlarnaPayLaterGateway extends Gateway {
	/**
	 * Gateway ID.
	 *
	 * @return string
	 */
	public static function id(): string {
		return 'pronamic_pay_klarna_pay_later';
	}

	/**
	 * Payment method.
	 *
	 * @return string
	 */
	public function get_payment_method(): string {
		return PaymentMethods::KLARNA_PAY_LATER;
	}
}
