<?php
/**
 * Gateway repository.
 *
 * Generated by `bin/generate-give-gateways.php` — do not edit manually.
 *
 * @author    Pronamic <info@pronamic.eu>
 * @copyright 2005-2026 Pronamic
 * @license   GPL-2.0-or-later
 * @package   Pronamic\WordPress\Pay\Extensions\Give
 */

namespace Pronamic\WordPress\Pay\Extensions\Give;

use Pronamic\WordPress\Pay\Core\PaymentMethods;

/**
 * Gateway repository class
 */
final class GatewayRepository {
	/**
	 * Map of Pronamic payment method to Give gateway class.
	 *
	 * @return array<string, class-string<Gateway>>
	 */
	public static function get_map(): array {
		return [
			PaymentMethods::AFTERPAY_COM            => Gateways\AfterpayComGateway::class,
			PaymentMethods::ALIPAY                  => Gateways\AlipayGateway::class,
			PaymentMethods::AMERICAN_EXPRESS        => Gateways\AmericanExpressGateway::class,
			PaymentMethods::APPLE_PAY               => Gateways\ApplePayGateway::class,
			PaymentMethods::BANCONTACT              => Gateways\BancontactGateway::class,
			PaymentMethods::BANK_TRANSFER           => Gateways\BankTransferGateway::class,
			PaymentMethods::BELFIUS                 => Gateways\BelfiusGateway::class,
			PaymentMethods::BILLIE                  => Gateways\BillieGateway::class,
			PaymentMethods::BILLINK                 => Gateways\BillinkGateway::class,
			PaymentMethods::BITCOIN                 => Gateways\BitcoinGateway::class,
			PaymentMethods::BLIK                    => Gateways\BlikGateway::class,
			PaymentMethods::BUNQ                    => Gateways\BunqGateway::class,
			PaymentMethods::IN3                     => Gateways\In3Gateway::class,
			PaymentMethods::CAPAYABLE               => Gateways\CapayableGateway::class,
			PaymentMethods::CARD                    => Gateways\CardGateway::class,
			PaymentMethods::CREDIT_CARD             => Gateways\CreditCardGateway::class,
			PaymentMethods::DIRECT_DEBIT            => Gateways\DirectDebitGateway::class,
			PaymentMethods::DIRECT_DEBIT_BANCONTACT => Gateways\DirectDebitBancontactGateway::class,
			PaymentMethods::DIRECT_DEBIT_IDEAL      => Gateways\DirectDebitIDealGateway::class,
			PaymentMethods::DIRECT_DEBIT_SOFORT     => Gateways\DirectDebitSofortGateway::class,
			PaymentMethods::EPS                     => Gateways\EpsGateway::class,
			PaymentMethods::FOCUM                   => Gateways\FocumGateway::class,
			PaymentMethods::IDEAL                   => Gateways\IDealGateway::class,
			PaymentMethods::IDEALQR                 => Gateways\IDealQrGateway::class,
			PaymentMethods::GIROPAY                 => Gateways\GiropayGateway::class,
			PaymentMethods::GOOGLE_PAY              => Gateways\GooglePayGateway::class,
			PaymentMethods::KBC                     => Gateways\KbcGateway::class,
			PaymentMethods::KLARNA                  => Gateways\KlarnaGateway::class,
			PaymentMethods::KLARNA_PAY_LATER        => Gateways\KlarnaPayLaterGateway::class,
			PaymentMethods::KLARNA_PAY_NOW          => Gateways\KlarnaPayNowGateway::class,
			PaymentMethods::KLARNA_PAY_OVER_TIME    => Gateways\KlarnaPayOverTimeGateway::class,
			PaymentMethods::MAESTRO                 => Gateways\MaestroGateway::class,
			PaymentMethods::MASTERCARD              => Gateways\MastercardGateway::class,
			PaymentMethods::MB_WAY                  => Gateways\MbWayGateway::class,
			PaymentMethods::MOBILEPAY               => Gateways\MobilepayGateway::class,
			PaymentMethods::MYBANK                  => Gateways\MybankGateway::class,
			PaymentMethods::PAY_BY_BANK             => Gateways\PayByBankGateway::class,
			PaymentMethods::PAYCONIQ                => Gateways\PayconiqGateway::class,
			PaymentMethods::PAYPAL                  => Gateways\PayPalGateway::class,
			PaymentMethods::PRZELEWY24              => Gateways\Przelewy24Gateway::class,
			PaymentMethods::RIVERTY                 => Gateways\RivertyGateway::class,
			PaymentMethods::SANTANDER               => Gateways\SantanderGateway::class,
			PaymentMethods::SOFORT                  => Gateways\SofortGateway::class,
			PaymentMethods::SPRAYPAY                => Gateways\SpraypayGateway::class,
			PaymentMethods::SWISH                   => Gateways\SwishGateway::class,
			PaymentMethods::TWINT                   => Gateways\TwintGateway::class,
			PaymentMethods::V_PAY                   => Gateways\VPayGateway::class,
			PaymentMethods::VIPPS                   => Gateways\VippsGateway::class,
			PaymentMethods::VISA                    => Gateways\VisaGateway::class,
		];
	}
}
